import React, { useState } from 'react';
import { Modal, Button, Form } from 'react-bootstrap';
import { addPatient } from '../utils/api';
import { Patient } from '../types';

interface AddPatientModalProps {
    show: boolean;
    handleClose: () => void;
    onPatientAdded: () => void;
}

const AddPatientModal: React.FC<AddPatientModalProps> = ({ show, handleClose, onPatientAdded }) => {
    const [name, setName] = useState('');
    const [dob, setDob] = useState('');
    const [sex, setSex] = useState('');
    const [height, setHeight] = useState('');
    const [weight, setWeight] = useState('');
    const [username, setUsername] = useState('');

    const handleAddPatient = async () => {
        const patientInfo: Patient = {
            name,
            dob: new Date(dob),
            sex,
            patientid: '', // This will be generated by the backend
            height: parseFloat(height),
            weight: parseFloat(weight),
        };

        const success = await addPatient(username, patientInfo);
        if (success) {
            onPatientAdded();
            handleClose();
        } else {
            alert('Failed to add patient');
        }
    };

    return (
        <Modal show={show} onHide={handleClose}>
            <Modal.Header closeButton>
                <Modal.Title>Add New Patient</Modal.Title>
            </Modal.Header>
            <Modal.Body>
                <Form>
                    <Form.Group controlId="formUsername">
                        <Form.Label>Username</Form.Label>
                        <Form.Control
                            type="text"
                            placeholder="Enter username"
                            value={username}
                            onChange={(e) => setUsername(e.target.value)}
                        />
                    </Form.Group>
                    <Form.Group controlId="formName">
                        <Form.Label>Name</Form.Label>
                        <Form.Control
                            type="text"
                            placeholder="Enter name"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                        />
                    </Form.Group>
                    <Form.Group controlId="formDob">
                        <Form.Label>Date of Birth</Form.Label>
                        <Form.Control
                            type="date"
                            value={dob}
                            onChange={(e) => setDob(e.target.value)}
                        />
                    </Form.Group>
                    <Form.Group controlId="formSex">
                        <Form.Label>Sex</Form.Label>
                        <Form.Control
                            type="text"
                            placeholder="Enter sex"
                            value={sex}
                            onChange={(e) => setSex(e.target.value)}
                        />
                    </Form.Group>
                    <Form.Group controlId="formHeight">
                        <Form.Label>Height (cm)</Form.Label>
                        <Form.Control
                            type="number"
                            placeholder="Enter height"
                            value={height}
                            onChange={(e) => setHeight(e.target.value)}
                        />
                    </Form.Group>
                    <Form.Group controlId="formWeight">
                        <Form.Label>Weight (kg)</Form.Label>
                        <Form.Control
                            type="number"
                            placeholder="Enter weight"
                            value={weight}
                            onChange={(e) => setWeight(e.target.value)}
                        />
                    </Form.Group>
                </Form>
            </Modal.Body>
            <Modal.Footer>
                <Button variant="secondary" onClick={handleClose}>
                    Close
                </Button>
                <Button variant="primary" onClick={handleAddPatient}>
                    Add Patient
                </Button>
            </Modal.Footer>
        </Modal>
    );
};

export default AddPatientModal;
